### ISSUE TITLE
Auto-fix wrapping does not indent imported values

### ISSUE THREAD

**Issue by realbizkit** [SeinopSys/eslint-plugin-import-newlines#10]
After the ESLint rule's auto-fix wraps the import statement into multiple lines, there are no indentations at the beginning of the new lines before the values: 

![image](https://user-images.githubusercontent.com/25567148/177060326-6b78362a-cdd2-4fb6-bdaa-e37e4fa163b7.png)

**Comment by SeinopSys** [comment]
You should also configure the `indent` built-in ESLint rule to enforce the indentation on these lines, this plugin only adds the new line characters and relies on the built-in rule by design, as per the readme:

https://github.com/SeinopSys/eslint-plugin-import-newlines/blob/f0d3a85f2694d28e3fba61d1772234fc16b3273e/README.md?plain=1#L100

Please feel free to reopen of you find another issue after configuring this rule.
