### ISSUE TITLE
Blank lines between imports

### ISSUE THREAD

**Issue by Cipscis** [SeinopSys/eslint-plugin-import-newlines#16]
Hi, I've just come across your package when searching for a way to standardise my import statements. I'm introducing it into one of my personal projects, and finding the best way to work with it. I really appreciate you having built and published this, so thank you!

I'm feeling a bit confused by one of the error messages reported by this rule, and I'm not sure if it's because it's a bug or if I've just misinterpreted the message.

When I import a lot of symbols from a single file, I will often separate them into sections by inserting a blank line between imports. For example:

```typescript
import {
	getAllDayInfo,
	getDayInfo,
	loadDays,
	saveDays,
	setDayInfo,

	createTask,
	loadTasks,
	saveTasks,

	loadDayTasks,
	saveDayTasks,
	setDayTaskInfo,

	exportData,
	importData,
} from 'data';
```

When I do this with the `import-newlines` plugin, it reports this error message:

> Import lines cannot have more than one blank line between them.

I'm finding this a bit confusing because I have exactly one blank line between my import lines, and no more. The error only goes away if I remove all blank lines from the import statement.

Is this the intended behaviour and I've just misunderstood the message? Or are single blank lines like this meant to be allowed, and this is a bug?

---

I'm aware there's an outstanding issue around line comments within import statements which is not easy to fix (#15) which unfortunately means I can't do something like turning these blank lines into line comments.

As far as I can tell from the documentation, there's no configuration option to allow a certain number of blank lines in import statements. Would a configuration option around this be something that could be added, perhaps?

**Comment by Cipscis** [comment]
I've had a crack at making a PR to add an `allowBlankLines` configuration option. Not sure if this is something you'd like to add or not, but hopefully having a PR will at least make this issue easier to close one way or another :)

**Comment by SeinopSys** [comment]
The issue is twofold, and while some aspects can be fixed I feel like this might be an uphill battle. The package was never meant to handle grouping of imports like this. Even if this specific error message can be suppressed like in your PR, if and when an autofix would apply from this package, your grouping will be lost as it will re-generate the import statement with no blank lines in-between when applying the fix.

The error message is unfortunately wrong, the code does check the difference between the line number at the end of the previous token and the line number at the start of the current one and compares it to see if it is `> 1`, but in reality if there are blank lines, that would actually cause the difference to be 2 or more, a difference of 1 means the two imports directly follow each other without blank lines.

I have updated the error message to be less confusing and also introduced a new `allowBlankLines` option to suppress this error in the latest v1.4.0 release. Please check if this solves your issue and if not, feel free to reopen this.
